FROM node:22-slim
WORKDIR /app
RUN corepack enable
COPY package.json yarn.lock .yarnrc.yml ./
RUN yarn install --immutable
COPY . .
# Next.js bakes NEXT_PUBLIC_* into the bundle at build time; pass as --build-arg.
ARG NEXT_PUBLIC_STAGE
ARG NEXT_PUBLIC_API_BASE
ARG NEXT_PUBLIC_CONTENT_ROOT
ARG NEXT_PUBLIC_MESSAGING_API_SOCKET
ARG NEXT_PUBLIC_B1ADMIN_ROOT
ARG NEXT_PUBLIC_LESSONS_API
ARG NEXT_PUBLIC_GOOGLE_ANALYTICS
ENV NEXT_PUBLIC_STAGE=$NEXT_PUBLIC_STAGE \
    NEXT_PUBLIC_API_BASE=$NEXT_PUBLIC_API_BASE \
    NEXT_PUBLIC_CONTENT_ROOT=$NEXT_PUBLIC_CONTENT_ROOT \
    NEXT_PUBLIC_MESSAGING_API_SOCKET=$NEXT_PUBLIC_MESSAGING_API_SOCKET \
    NEXT_PUBLIC_B1ADMIN_ROOT=$NEXT_PUBLIC_B1ADMIN_ROOT \
    NEXT_PUBLIC_LESSONS_API=$NEXT_PUBLIC_LESSONS_API \
    NEXT_PUBLIC_GOOGLE_ANALYTICS=$NEXT_PUBLIC_GOOGLE_ANALYTICS
RUN yarn build
EXPOSE 3000
CMD ["yarn", "start"]
