on:
  schedule:
    - cron: '10 8 * * 1'
  workflow_dispatch:

name: Deploy Prod

permissions:
  contents: write

jobs:
  deploy:
    name: Merge main to production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Merge main to production
        uses: devmasx/merge-branch@854d3ac71ed1e9deb668e0074781b81fdd6e771f # v1.4.0
        with:
          type: now
          from_branch: main
          target_branch: production
          github_token: ${{ secrets.GITHUB_TOKEN }}