on:
  schedule:
    - cron: '10 8 * * 1'
  workflow_dispatch:

name: Deploy Prod

jobs:
  deploy:
    name: Merge main to production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Merge main to production
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          target_branch: production
          github_token: ${{ secrets.GITHUB_TOKEN }}